jenkinsci/bitbucket-branch-source-plugin

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
`revision.getHash()` is null when using v3.x.x of the server
The following stacktrace happens in this case:
```
Started by user xxxxx (xxxx) 
java.lang.NullPointerException 
at org.eclipse.jgit.lib.ObjectId.fromString(ObjectId.java:231) 
at jenkins.plugins.git.AbstractGitSCMSource$SpecificRevisionBuildChooser.<init>(AbstractGitSCMSource.java:388) 
at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.build(BitbucketSCMSource.java:411) 
at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:80) 
at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:206) 
at hudson.model.ResourceController.execute(ResourceController.java:98) 
at hudson.model.Executor.run(Executor.java:410) 
Finished: FAILURE 
``` …
> [FIXED JENKINS-34365] Not able to resolve hash of the revision

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
A repository scan over our 100+ repos throws SSL exception errors. This was likely caused by running out of connections. I have modified invocation of HttpClient. It now uses a connectionmanager. As a result no more connection failures and the repo scan is a bit faster.
> Re-use connections to improve stability of repository scanning

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
@amuniz this updates the Build Status notifier to use the urls generated from the `DisplayURLProvider`. This is needed for Blue Ocean compatibility.
See https://github.com/jenkinsci/display-url-api-plugin
@jenkinsci/code-reviewers
> Update to use DisplayURLProvider

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketPushEvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPushEvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/BitbucketSCMSourcePushHookReceiver.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/BitbucketType.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PushHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerWebhookPayload.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/events/BitbucketServerPullRequestEvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/events/BitbucketServerPushEvent.java
[JENKINS-33507](https://issues.jenkins-ci.org/browse/JENKINS-33507)
I made some changes to the code to enable more support for Bitbucket server.
I also made a plugin for Bitbucket which is currently submitted for approval. When both installed Bitbucket can successfully send events to the jenkins machine. 
See [bitbucket-webhooks-plugin](https://github.com/topicusfinan/bitbucket-webhooks-plugin) repo for more information about the Bitbucket plugin.
[The plugin is also accepted by atlassian.](https://marketplace.atlassian.com/plugins/nl.topicus.bitbucket.bitbucket-webhooks/server/overview)
@reviewbybees
> [JENKINS-33507] Add support for the Bitbucket server.

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
When specifying a 'Bitbucket Server URL' with a base path, the base path is currently ignored when generating the checkout repository urls. End result is all your repositories fail to find any repos.
e.g. if you specify 'https://xxx.corp.com/stash' you receive
```
stderr: fatal: repository 'https://xxx.corp.com/scm/project/repo.git/' not found
```
as the correct git url is https://xxx.corp.com/stash/scm/project/repo.git/
> generated checkout url ignore base context path

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
Atlassian told us back in January that:
> This plugin uses https://bitbucket.org/api/.. as it's base URL. This is not a valid or even supported URL on Bitbucket. It currently happens to work, but won't in the future.
> As per the documentation, Bitbucket's API lives on https://api.bitbucket.org
See the [developer docs](https://confluence.atlassian.com/bitbucket/use-the-bitbucket-cloud-rest-apis-222724129.html#UsetheBitbucketCloudRESTAPIs-URIStructureandMethods).
PTAL @stephenc
> JENKINS-41190 Use new API endpoint instead of deprecated endpoint

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
When a Bitbucket Cloud or Server repository is scanned and the repository has no branches, the endpoint describing the 404 will fail causing the scan to fail.
See [JENKINS-45632](https://issues.jenkins-ci.org/browse/JENKINS-45632)
PTAL @stephenc @vivek
> JENKINS-45632 Handle when default branch is not found

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
In BitbucketServer 4.5.1, the BitbucketTeam (which is a BitbucketServerProject) has no link named 'html' (only a 'self' link, which is good) and the team link fallback to '/NAME', but it should be '/projects/NAME'.
> Fix project/team URL in BitbuckerServer

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
An Atlassian team member explains that there currently is no way to predict when rate limiting will occur on this page: https://community.atlassian.com/t5/Answers-Developer-Questions/Finding-out-request-left-until-I-hit-the-API-rate-limit/qaq-p/549595
Therefore I've created a simple fix in the `BitbucketCloudApiClient.getRequest(...)` which does a sleep and a retry when status code `429` is returned.
> Added a simple sleep and retry loop when rate limiting occurs

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
This mimics the cloud API behavior and enables, for example, repos with more than 100 pages of branches to get them all scanned.
> Consume all pages of data instead of stopping after 100

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
Increment page start parameter during recursive call to fetch directory listing page. This can cause the loop to never break for repo directory with number of files > 500.
See [https://issues.jenkins-ci.org/browse/JENKINS-48279](JENKINS-48279).
cc: @casz @stephenc
> JENKINS-48279# Update start of page in directory listing

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
Previously, if you were not on a team for a repository you had to be the owner to select it as the build source in Jenkins. I can't compile this to test, but this should let you select repositories you're also a contributor on instead.
> JENKINS-45836 Allow Contributors to select repositories to build

- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/Messages.properties
In current HEAD, there is a spelling error in an error message when configuring branch sources for a job through the user interface:
This code change address that to spell out the words "or" and "does" with a space in between:
> Fixed spelling error in job configuration branch source error message

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
See [JENKINS-38664](https://issues.jenkins-ci.org/browse/JENKINS-38664)
Closes #22
> [FIXED JENKINS-38664] Skip notification if root URL not defined

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/repository/BitbucketRepositorySource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFile.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
Bitbucket Cloud 2.0 API to get source (file/directory) content should be in context of revision hash and not branch name. 
`https://api.bitbucket.org/2.0/repositories/owner/repository/src/{node}/{path}`
I checked with BB cloud API team, the node parameter could be simple branch name but not all. Safe to use hash to have it work in all cases.
cc: @stephenc
> JENKINS-47978# Fix handling branch name with '/'

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/branch/BitbucketCloudBranch.java
For Hg repositories, Bitbucket returns all branches, including the closed/inactive ones.
To filter the closed branches out, we have a look at the 'heads' property in the json response:
- Branches with non-empty heads are active.
- Branches with empty heads are inactive.
- On branches from git repositories heads is null. They all are active.
> [FIX JENKINS-47958] Filter closed Hg branches out

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/pullrequest/BitbucketServerPullRequest.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/pullrequest/BitbucketServerPullRequestCanMerge.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint/config-detail.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint/help-callCanMerge.html
This is needed to make sure that the git references are up to date.
> JENKINS-45997: check mergability when retrieving pull requests

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigatorRequest.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketProject.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketRepository.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/repository/BitbucketCloudRepository.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/repository/BitbucketServerRepository.java
Hi,
I have written a trait to filter Bitbucket cloud projects as originally tried on PR https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/16.
However, it was suggested that such traits could be an extension plugin. I will implement such plugin but I need more information to be available so a trait can filter a project without doing any more additional API calls.
This changes here are adding the BitbucketRepository object to a request, that can later be filtered by a trait. I also included additional JSON fields to parse the project.
I have tested this with both Bitbucket server and cloud.
I have not added or changed any test cases as I do not see any tests testing the parts I have changed, please advise, if necessary I can add them.
Thanks.
> Adding Bitbucket repository information to request to allow traits to filter by project

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
Avoid build status API calls if the server is running on localhost. 
That is because this is displayed on the Bitbucket UI with a link, that will fail if pointing to localhost. 
This serves as a protection in case developers are testing something on their machines, and therefor might not want to notify the server. 
A similar protection already exists for registering web-hooks on WebhookAutoRegisterListener.
> Avoid build status API calls if the server is running on localhost

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
Change the "The tests have started" message to "The build is in
progress". This would be more generic and better, because what we
actually do is we start some Jenkins build, that can include tests,
deployment, etc.
> JENKINS-52138 Change the BitBucket status message for "In progress"

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketPullRequest.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/pullrequest/BitbucketPullRequestValue.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/pullrequest/BitbucketServerPullRequest.java
BitBucket server allows us to get a pull request author's email
from pull requests payloads. This means that we're able to set the
CHANGE_AUTHOR_EMAIL Jenkins environment variable. And, using
this, we'll be able to, for example, send emails from pull request
right to pull requests authors.
> Add the ability to use the CHANGE_AUTHOR_EMAIL environment variable

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
Motivation
----------
When #92 upgraded `HttpClient` to version 4.x, the connection and socket timeouts were [apparently] correctly preserved in `BitbucketCloudApiClient` (see [here](https://github.com/jenkinsci/bitbucket-branch-source-plugin/commit/8f81d4026153e7ee250252180c34ed2eaa7a784f#diff-66513375f9e876a8924d023aea79a71bR147) and [there](https://github.com/jenkinsci/bitbucket-branch-source-plugin/commit/8f81d4026153e7ee250252180c34ed2eaa7a784f#diff-66513375f9e876a8924d023aea79a71bR667)), but `BitbucketServerAPIClient` only had  its timeouts preserved for non-GET requests (i.e. POST, PUT, etc. whatever called `#doRequest`) and the default timeout is `0` (infinite).
This has lead our Jenkins instances to get stuck whenever our Bitbucket Server instance would not answer (which happens …
> Restore timeouts in BitbucketServerAPIClient

- pom.xml
We should be using the Jenkins plugin version of Jackson
A extension of #143's discussion
> lower Jackson dependency to 2.7.3 for java 7

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
Bitbucket allows providing a description in the status, currently this gets set as a default hard coded string. For backwards compatibility, but allowing for detailed messages, use the hard coded string with the build description appended.
> Append build description to bitbucket status description

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessor.java
CHANGE_BRANCH is correct on bitbucket cloud but not bitbucket server, maybe a typo in origin PR #63  ? cc @zigarn for review
CHANGE_BRANCH is set in branch-api-plugin from getOriginName() 
```
if (head instanceof ChangeRequestSCMHead2) {
envs.putIfNotNull("CHANGE_BRANCH", ((ChangeRequestSCMHead2) head).getOriginName());
}
```
> fix JENKINS-47617 CHANGE_BRANCH should return source branch name

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
It looks like a confusion of BitbucketSCMSource.MercurialRevision and MercurialSCMSource.MercurialRevision.
> JENKINS-52134: check correct rev class when sending build status

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/JsonParser.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketPushEvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPushEvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PushHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/events/BitbucketServerPushEvent.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketDateFormatTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClientTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/DateUtils.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPushEventTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClientTest/getRepositoryPayload.json
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPushEventTest/newTagPayload.json
Manage TagSCMHead correctly when bitbucket payload webhook is of king create tag.
Fix parsing of ISO8601 date in BB payload. Handle also non ISO8601 standard date for updateOn field.
To avoid too regression only the new date fields are of kind Date the other one are keep as is. If changed to Date in the future they works, otherwise in case the Bitbucket date format can be enhanced to handle other cases.
> JENKINS-51063 the PushHookProcessor does not handle correctly webhook of kind tag

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketHgSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketClientMockUtils.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilderTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/UriResolverTest.java
- src/test/java/integration/ScanningFailuresTest.java
https://issues.jenkins-ci.org/browse/JENKINS-47283
**Motivation:**
Some Bitbucket Server installations use clone URLs that are completely different from the URLs used for web-based access. The clone URLs are correctly advertised via the REST interface, but the the plugin solely uses them to determine alternate port numbers. This leads to SCM checkout failures during builds, since the SCM remote URLs determined by the plugin are wrong.
**Modifications:**
Pass on the whole clone link to BitbucketApi::getRepositoryUri, instead of just passing on the pre-parsed port number. Let implementors decide what to do with this extra piece of information:
* Cloud: just ignore
* Server: Just use if cloning via SSH: Use the scheme and authority (which includes user, host and port number) from the clone …
> JENKINS-47283: Use more information from clone links when determining SCM URLs.

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTest.java
Fix case when the Jenkins URL is a hostname but not localhost, and the Bitbucket API doesn't allow it
For example, my Jenkins instance runs at http://intranet:8080.
When calling directly Bitbucket API with this URL, the API response is :
`{"type": "error", "error": {"fields": {"url": ["Enter a valid URL."]}, "message": "url: Enter a valid URL."}}`
So I propose to change the Jenkins root URL verification check to handle this case.
> Fix bad Jenkins root URL for Bitbucket API

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
This PR is about marking not built Jenkins builds as not failed but instead succeeded in Bitbucket. Unfortunately Bitbucket has only 3 states (SUCCESS, FAILURE and INPROGRESS) so therefore I decided to map NOT_BUILT to SUCCESS.
Similar solution was as well taken in the Stash Notifier Plugin: https://github.com/jenkinsci/stashnotifier-plugin/pull/116
> [JENKINS-49640] Do not mark builds in NOT_BUILT state as failed

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/SCMHeadWithOwnerAndRepo.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketApiFactory.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketAuthenticator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketClientCertificateAuthenticator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketClientCertificateAuthenticatorSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketUsernamePasswordAuthenticator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketUsernamePasswordAuthenticatorSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiFactory.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/AbstractBitbucketEndpoint.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/AbstractBitbucketEndpointDescriptor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketCloudEndpoint.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookAutoRegisterListener.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerApiFactory.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketAuthenticatorTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketMockApiFactory.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/UriResolverTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketIntegrationClientFactory.java
Opening for initial feedback.
This is based on #92 and moves to using the AuthenticationTokens plugin as was suggested in a couple of other pull-requests (#69, #68, and #94). This also includes support for client certificates like #94.
> Use AuthenticationTokens

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
* in BitbucketSCMSource it's named "General"
* both help files use "General"
* .../BitbucketSCMNavigator/help-traits.html
* .../BitbucketSCMSource/help-traits.html
> Name sections consistently

- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint/config-detail.jelly
[https://issues.jenkins-ci.org/browse/JENKINS-55787](https://issues.jenkins-ci.org/browse/JENKINS-55787)
Basically checkboxes should have labels, splitting the labels away from their checkboxes is poor UX, poor accessibility. This change brings the layout more inline with how normal settings UIs lay out checkboxes.
> [JENKINS-55787] Switch labels from entry to checkbox

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFile.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClientTest.java
Fixing lightweight checkout for PRs for merge and head revisions. The easiest way seemed to pull more data (SCMHead) into BitbucketSCMFile to be able to distinguish between merge and head PRs in a central location. 
Validated on Atlassian Bitbucket Server (DC) v5.8.2 for Jenkinsfiles as well as arbitrary files directly in a repo as well as in subdirectories.
There's still the corner case left for lightweight checkouts on conflicted PRs - these are still checked out in full, also on Jenkins masters.
> JENKINS-48737 Fixing lightweight pull request checkouts, also for files in subdirectories

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/WebhookConfigurationTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/Messages.properties
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/WebhookConfigurationTrait/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/WebhookConfigurationTrait/help.html
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/WebhookConfigurationTraitTest.java
- Adds a trait to allow setting of the committersToIgnore value
- Adds unit tests for setting of the value
- Adds a property accessor to the WebhookConfiguration for testing
- Adds resource definitions to allow setting in the UI
- [x ] Please describe what you did
- [x ] Link to relevant GitHub issues or pull requests
- [x ] Did you provide a test-case? That demonstrates feature works or fixes the issue.
Add a WebhookConfigurationTrait to allow setting of the committersToIgnore value of the WebhookConfiguration class. This makes it possible to set and persist the value of field for the Bitbucket Webhook. Without this exposure there is no way to set and maintain the setting on the Webhook as the current implementation does not set it, and always overwrites what is set on the server (since …
> JENKINS-47867 Add WebhookConfigurationTrait

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
Fixes #213 by configuring the Apache HttpClient to retry idempotent http requests. When creating the HttpClient, the `StandardHttpRequestRetryHandler` from the Apache HttpClient is registered as retry handler meaning every idempotent request (e.g. GET, HEAD, ...) will be automatically retried 3 times.
We believe this makes the plugin more resilient to stale connections and/or intermittent network failures.
> Retry idempotent requests.

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
No. I don't see any good way to test this. Would need a simulation of the external systems involved... a NAT box that doesn't RST severed connections?
The default behaviour of `PoolingHttpClientConnectionManager` is to inspect the server-provided `Keep-Alive` header and use it as the basis for auto configuring the `ConnectionKeepAliveStrategy`, and in the absence of such a header assumes the connection can be kept alive indefinitely.
api.bitbucket.org does not produce a `Keep-Alive` header.
This is a simple patch to hardcode a more aggressive 5-second ConnectionKeepAliveStrategy.
Fixes #217
> 5 second ConnectionKeepAliveStrategy

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPushHookProcessor.java
Able to detect a tag creation from the Bitbucket PushHead Event and automatically create tags in Jenkins. This allows the workflow to build projects when tagging and/or pushing a commit.
This changeset adds a tag detection branch logic in the **NativeServerPushHookProcessor.HeadEvent**'s **heads** function.
> [JENKINS-57516] - Support tag creation on tag push

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/SSHCheckoutTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/AbstractBitbucketEndpoint.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/AbstractBitbucketEndpointDescriptor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfiguration.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketClientMockUtils.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigatorTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchScanningIntegrationTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchScanningTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketCloudEndpointTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpointTest.java
> Update parent pom, update jenkins core, use bom

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/payload/2.0-repositories-amuniz-test-repos-hooks_page_1_pagelen_100.json
In our organisation we use a the technical user allowed to access all repositories in BB cloud.
All jenkins job are of type "multi branch pipeline" and we have about 360 repositories. In the last month we often get the BB cloud rate limit exceed issue.
We are organising all repositories under more organisation folders and the rate limit issue causes the total block of webhooks processing because it get stucks during the retrieve of the list of repositories
Actually the pagelen is setup 50 that means for 360 repos 8 calls. In BB documentation the max allowed pagelen is 100. I started making this limit configurable but seems does not have sense. Like for client server side I would use the max available page size (or limit) available to get as less as possible the rate limit exceed issue.
> Set the page length to the max allowed for Bitbucket Cloud REST APIs

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketUsernamePasswordAuthenticator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
Keep previously set values in context / AuthCache
and
limit the httpCredentials to bitbucket only.
> Keep bitbucket credentials with proxy

- README.adoc
- pom.xml
I decided not to migrate the changelog 😓 
The rest of the content is outdated and Cloudbees maintain a decent user guide.
Only thing missing from the user guide is how to configure the plugin from JCasC 😄
> migrate wiki content to github

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BranchDiscoveryTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/ForkPullRequestDiscoveryTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/OriginPullRequestDiscoveryTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/PublicRepoPullRequestFilterTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/SSHCheckoutTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/TagDiscoveryTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/WebhookConfigurationTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/WebhookRegistrationTrait.java
Now all traits consistently have a `@Symbol` annotation.
This improves configuration with JobDSL. Otherwise there is a clash e.g. with the github-branch-source-plugin.
Also see https://github.com/jenkinsci/github-branch-source-plugin/pull/258.
> [JENKINS-45504] - Add @Symbol annotations to traits

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BranchDiscoveryTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/ForkPullRequestDiscoveryTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/SSHCheckoutTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/TagDiscoveryTrait.java
Also see https://github.com/jenkinsci/github-branch-source-plugin/pull/256.
> Make common traits consistent with github-branch-source-plugin

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
> Fixing NullPointerExceptions in PullRequests

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
provide the reason why Jenkins cannot determine the Jenkins root URL
refs https://issues.jenkins-ci.org/browse/JENKINS-54297
> feat: be more verbose in build status notification exception

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
Added a condition for Issue 273 so that permisisons issues dont break your branch indexing completely
The goal is to fix https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/273#issue-553545339 where the branch indexing was broken when the user didnt have access to a specific branch. Also it helps if there is any situation where a auth failure happens with something like API limits
- [ ✅] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [  ✅] Ensure that the pull request title represents the desired changelog entry
- [ ✅ ] Please describe what you did
- [ ✅ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ❌ ] Did you provide a test-case? That demonstrates feature works …
> Added condition for 403 HTTP Status

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
Reverts the changes made to traits in 2.6.0 release
as it prevents JobDSL from working with traits
fixes #258
> fix Job DSL by adding a DataboundSetter it can understand

- docs/USER_GUIDE.adoc
I use the webhook feature with bitbucket server, so obviously the information seems to be outdated.
> Remove wrong information about the webhook feature

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/pullrequest/BitbucketPullRequestValueDestination.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/payload/2.0-repositories-amuniz-test-repos-pullrequests_page_1_pagelen_50.json
This PR attempts to address issue #205. In that issue, Jackson cannot deserialize the pull requests JSON response because one or more PRs have a null value for the destination branch. The constructor for `BitbucketPullRequestValueDestination` would throw a NullPointerException assuming that branch was never null. The fix for deserialization is as simple as a null check in the `BitbucketPullRequestValueDestination` constructor.
Fixing deserialization introduces a new problem. Several areas of the code depend on the PR having a valid destination. Rather than adding null reference handling every time a piece of code needs the destination branch, I removed these invalid PRs from the result set before passing it off to the plugin. I don't believe this should cause any problems because these …
> PRs without a valid destination branch no longer break SCM scanning.

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketPullRequest.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/pullrequest/BitbucketPullRequestValue.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketClientMockUtils.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/createPayloadFork.json
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/createPayloadOrigin.json
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/fulfilledPayload.json
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/rejectedPayload.json
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/updatePayload_newCommit.json
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/updatePayload_newDestination.json
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest/updatePayload_newDestinationCommit.json
Fixes #195, which is not a plugin regression, but a [cloud API regression](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/) to satisfy GDPR. There is apparently no way to set `CHANGE_AUTHOR` to the previous value. (`CHANGE_FORK`, or its first component if `/`-separated, is probably the same thing, though this is not necessarily the _author_.) Nor is `CHANGE_AUTHOR_EMAIL` possible.
Also, for Server, the display name was mistakenly being bound to the variable intended for the (code) username.
Example variables with BB Cloud, before:
```
(no variables starting with CHANGE_AUTHOR)
```
after:
```
CHANGE_AUTHOR=123456:some-long-uuid
CHANGE_AUTHOR_DISPLAY_NAME=Jesse Glick
```
With BB Server 7, before:
```
CHANGE_AUTHOR=Test User …
```
> Fix CHANGE_AUTHOR and CHANGE_AUTHOR_DISPLAY_NAME

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookEventType.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPullRequestHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java
Add support for a new event type introduced by Bitbucket Server 7 `pr:from_ref_updated`.
Behaviour should be the same as any update to pull requests as created in https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/291
fixes #308 by adding support for incoming event type `pr:from_ref_updated` and processing it the same as `pr:modified`.
> add support for server event `pr:from_ref_updated`.

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/pullrequest/BitbucketPullRequestValueDestination.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/pullrequest/BitbucketPullRequestValueRepository.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/payload/2.0-repositories-amuniz-test-repos-pullrequests_page_1_pagelen_50.json
Fix NPEs caused by deleted source and destination branch or repository of PRs.
* [JENKINS-62780](https://issues.jenkins-ci.org/browse/JENKINS-62780)
* [JENKINS-57775](https://issues.jenkins-ci.org/browse/JENKINS-57775)
* https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/283
Tested the different scenario against Bitbucket Cloud and confirmed that:
* `source.repository` can be `null` (deleted source repository)
* `source.commit` can be `null` (deleted source repository)
* `destination.commit` can be `null` (deleted destination branch)
I haven't been able to reproduce a nullable `source.branch` or `destination.branch`.
When testing against Bitbucket Server (7.2.1), I could not reproduce such scenario:
* PR opened from deleted source branch or forked are automatically declined. …
> [JENKINS-57775][JENKINS-62780] Handle PRs from/to non existing src/dest

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketOAuthCredentialMatcher.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketOAuthCredentialMatcherTest.java
https://issues.jenkins-ci.org/browse/JENKINS-63401
The current behaviour can break anyone using GitHub apps from changing the rate limit strategy.
TBH it's probably a bug in core too as returning a 500 from a doFill method probably shouldn't cause the JavaScript to break...
But an easy fix here
cc @jetersen @bitwiseman
> JENKINS-63401 Harden looking up credentials

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookEventType.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/BitbucketServerVersion.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfigurationTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest/configuration-as-code.yml
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfigurationTest/configuration-as-code.yml
Reorganize hook events for different BitBucket versions and introduce settings for versions 7, 6, 5.10 and earlier than 5.10
Version 2.80 accidentally added some default hook events that are only available on version 5.10+
Tested against BB v5.4
Fixes #352
> Fix Automatic Webhook Creation for BitBucket 5.x [Fixes 352]

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketOAuthCredentialMatcher.java
Do not match on instances of AmazonECSRegistryCredential
> JENKINS-64183 fillCredentialsIdItems fails if Amazon ECR is installed

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTest.java
Experimentation with a plugin usage tool looking for `Run.actions` found that this plugin was attaching its action to every build even when Bitbucket was not in use. Corrects a regression in #130 by @michelzanini.
> Only add FirstCheckoutCompletedInvisibleAction if this build is using BitbucketSCMSource

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
Fixes issue #335
Added a fallback to the first configured Bitbucket Server (if <0 present), before falling back to Bitbucket Cloud, as proposed in #335  by [rbywater](https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/335#issuecomment-709678249).
The implementation differs from his proposal as I calculate the default value for serverUrl in a variable before calling `serverUrl = StringUtils.defaultIfBlank(serverUrl, serverUrlFallback);` for better readability.
Tested on our infrastructure (Jenkins 2.263 and on premise Bitbucket Server 7.6.0). 
**Testprotocol**
- recreate error described in #335 with plugin version 2.9.4. 
- installing new build with proposed change (+restart jenkins)
- Test configuring branch source with 1 bitbucket server in global config -> repository …
> fixed #335: Unable to create new multibranch pipeline project (Error while loading repositories from cache)

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfiguration.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HasPullRequests.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPullRequestHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPushHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-pull-requests-1.json
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-pull-requests-2.json
There are several cases where all PRs are fetched or PRs are fetched again and again.
**#443 all PRs are fetched (multiple times even) on webhook event**
* Ignore repos that don't match the event
* Instead of fetching all PRs again, reuse the PR information that is already present from the Webhook.
**[JENKINS-65719](https://issues.jenkins.io/browse/JENKINS-65719) Jenkinsfile Retrieval for a PR should not check on All PRs**
* Instead of fetching all PRs, only fetch the relevant one
> Avoid fetching all PRs

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
PR https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/214 introduced retries for requests to Bitbucket cloud. This PR makes the same change for Bitbucket Server requests, because I'm currently dealing with an unreliable Bitbucket Server.
> Retry idempotent requests to Bitbucket server

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceContext.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketBuildStatus.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTrait/config.jelly
Current implementation notifies the BitBucket as successfull, the case build was aborted. If BitBucket has a "need at least one successfull build" as quality gate for pull-request merge, then aborted builds will fulfill the quality gate. This PR solves the issue, that no notification is performed.
- [ X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [ X] Ensure that the pull request title represents the desired changelog entry
- [ X] Please describe what you did
Signed-off: alexander.falkenstern@gmail.com
> Avoid "Success" Bitbucket notification, case build was aborted

- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java
As there is no way to make simple code that works for both Guava 11 and 31. I could wait for `2.332.1` to be released, update the baseline and make all the needed changes in the code to the new Guava classes, but in two years I will have to do it again...
Note this is affecting only a test, no production code, so just running the test proves it works.
> Replace Guava's Files.copy with commons FileUtils in test

- docs/USER_GUIDE.adoc
Users (and myself) were having trouble using App passwords after Bitbucket deprecated usage of Atlassian account passwords in Git over HTTPS and API. 
See [issue 573](https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/573)
Mainly the cause was the use of email address as the username. To avoid confusion, I added a section with instructions on using App passwords emphasizing on use of _username_ instead of email address.
> Added instructions on using Bitbucket App Passwords to the user guide.

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceRetrieveTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceRetrieveTest/retrieve_prs_test_cloud.xml
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceRetrieveTest/retrieve_prs_test_server.xml
Proposed fix for the problem raised in [ issue #469](https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/469) regarding fork-based PRs not triggering builds.  In order for a commit hash from a fork-based PR to be made visible in the target repo, a call to the `/changes` API must be made.  The fix was based on comments found in [BitbucketServerAPIClient.setupPullRequest()](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java#L338-L362) which were discussed with and confirmed by Atlassian support.
A new unit test has been provided that exercises code paths within `BitbucketSCMSource.retrieve(SCMSourceCriteria, SCMHeadObserver observer, SCMHeadEvent, …
> fix: call the /changes API to make the commit hash available in the target repo

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigatorRequest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/SCMNavigatorTest.java
This changes the behaviour of the organisation scan so that newly discovered repositories are processed first.
- [  ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [  ] Link to relevant pull requests, esp. upstream and downstream changes
When team folders get to several hundred repositories in size, adding new ones can take many hours to be processed and added by the organisation scan. This change ensures they are done first, meaning newly created repositories can be integrated into CI chains much sooner than otherwise.
> Organisation Folder Scan - newly discovered repositories are now processed first

- pom.xml
4.43 contain updated version of html-unit which should fix flickering in com.cloudbees.jenkins.plugins.bitbucket.Security2033Test.doClearWhenInvokedUsingGetMethodThenResourceNotFound
and com.cloudbees.jenkins.plugins.bitbucket.Security2467Test.doFillRepositoryItemsWhenInvokedUsingGetMethodThenReturnMethodNotAllowed
Issue [link](https://github.com/HtmlUnit/htmlunit/issues/385).
> update plugin from 4.39 to 4.43.1

- pom.xml
As recommended here: https://github.com/jenkinsci/maven-hpi-plugin/releases/tag/maven-hpi-plugin-3.28
> Remove java.level from pom

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketRepository.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/repository/BitbucketCloudRepository.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/repository/BitbucketServerRepository.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClientTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos_start_0_limit_200.json
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-foo-repos_start_0_limit_200.json
Bitbucket server 8.0 introduced the ability to archive repositories. An archived repository makes it read-only as well as other restrictions.
https://confluence.atlassian.com/bitbucketserver/archive-a-repository-1128304317.html
This change filters out archived repositories from the returned repositories list.
Fixes #703
> Exclude archived repositories

- README.md
The badge image shows "no longer available".
LGTM.com shut down its badge service on December 16, 2022.
It recommends using GitHub code scanning instead, and that was already added in <https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/656>.
AFAIK no issue has been filed.
Don't need a test case for a doc change.
> Delete lgtm badge from README

- .gitattributes
In .gitattributes, set `crlf=input` for `*.java` and `*.properties`, so that:
* "git checkout" does not convert newlines, so they remain LF, even if the system Git configuration on Windows specifies core.autocrlf=true.
* "git add" converts CRLF to LF.
This fixes the numerous checkstyle errors about CRLF newlines that show up in the console log of ci.jenkins.io when it builds the plugin on Windows.  Stuff like these:
```
[2023-09-16T18:26:36.688Z] [INFO] --- checkstyle:3.3.0:check (default) @ cloudbees-bitbucket-branch-source ---
[2023-09-16T18:26:45.633Z] [INFO] There are 201 errors reported by Checkstyle 10.12.3 with C:\Jenkins\agent\workspace\cket-branch-source-plugin_master/checkstyle.xml ruleset.
[2023-09-16T18:26:45.737Z] [ERROR] …
```
> Make Git use LF newlines in *.java, *.properties

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/BitbucketSCMSourcePushHookReceiver.java
When receiving a webhook request at bitbucket-scmsource-hook and converting the HTTP request body to a string, always use UTF-8 even if the system default charset is different.
This is mainly relevant to a Jenkins controller running on Windows, where the system charset might be Windows-1252, but Bitbucket Server encodes the webhook request JSON in UTF-8.
Fix <https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/762>
> Decode webhook request body as UTF-8

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
Use hash to get files from BB server API, currently we always use ref that leads to reading files from incorrect places e.g. if you use `readTrusted` in long running pipeline and revision of ref changes during execution. It seems logical to use revision here as we should always have revision specification in multibranch pipeline runs.
- [ x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [ x] Please describe what you did
> Use revision to get files from bitbucket api

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClientTest.java
I've identified an issue in the HttpClient configuration when interacting with Bitbucket Server. Encountering a warning: "WARNING ... processCookies: Invalid cookie header." This warning is triggered during the cookie parsing process, which seems to be incompatible with the cookie formats sent by Bitbucket Server.
Initially, I considered changing the default cookie specification to CookieSpecs.STANDARD to address this compatibility issue. However, I realized that this might not be the most efficient solution. Current code seems to create a new cookie store for each request.
Therefore, to simplify the HTTP interactions and eliminate the warning, I've opted to deactivate cookie handling in the HttpClient when interacting with Bitbucket Server. By disabling cookie management, we not only …
> Fix for "Invalid cookie header"-warning using HttpClient and Bitbucket Server Interaction

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketRepositoryProtocol.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilderTest.java
In Bitbucket Server "http" is used as http link name, but in Bitbucket Cloud "https" is used.
Bug was introduced in #796. Fixes #804.
> Properly handle value "https" in clone link name

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketAuthenticator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketOAuthAuthenticator.java
Problem was introduced in #796. Fixes #808.
It's hard to write test for BitbucketOAuthAuthenticator because of statically called service methods.
> Add OAuth token to http clone link

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilderTest.java
Makes RefSpecsSCMSourceTrait working again.
Fixes #814.
See also #812.
Problem was introduced in #796.
> Remove ref-specs cleanup during initialization of BitbucketGitSCMBuilder

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/PullRequestSCMRevision.java
The signature change in recent release caused `NoSuchMethodError` in plugins that are compiled against the old code.
I've tested it with the PCT and ATH of the affected plugin (cloudbees internal).
> Fix binary compatibility for PullRequestSCMRevision.getPull

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
Previously token was fetched only once and saved in BitbucketSCMSource.
Fixes #808.
See also #810 and #796.
> Get fresh oauth token on every git clone

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
Use the checkoutCredentialsId if available so that the credentials are an instance of SSHUserPrivateKey, the protocol switches to ssh and getCloneLink do not fail. This should fix #811
> Fix checkout over ssh

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
Commit information, identiefied by the has, does not change over time. Therefore, introduce a cache and add the information once it is retrieved first.
- No, as I am not sure how to write those.
Fixes #838
> Add cache for commit responses based on hashes

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketApiUtils.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/SSHCheckoutTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/AbstractBitbucketEndpointDescriptor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfiguration.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java
Adapt plugin to allow user with Overall/Manage to configure global settings under `Manage Jenkins` --> `System`
Jenkins Issue -> https://issues.jenkins.io/browse/JENKINS-73038
> [JENKINS-73038] Adapt plugin to allow user with Overall/Manage to configure global settings

- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketAuthenticatorTest.java
adapt to https://github.com/jenkinsci/credentials-plugin/pull/543
> adapt tests to upstream KeyStore validation

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
Bug was introduced in https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/839, as discussed here https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/839#pullrequestreview-1976010981
In order to log the exceptions, they have to be thrown. In the previous PR, all exceptions were caught by a catch block, and null was returned. This is not the behavior from the before the PR.
Fixes #850
> Fix removal of exception throwing in BitbucketCloudApiClient.java

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
If a requests is sent with a project key, and the key is not part of the cache key, following requests for other projects will result in the cached repositories for the first project, leading to wrong results
- No, as I don't know how to write such a test case.
Fixes #836
> Add project key to cache key

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketAuthenticator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketAccessTokenAuthenticator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketOAuthAuthenticator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketUsernamePasswordAuthenticator.java
This is the first part of fix #867 to reapply fix for JENKINS-73677 in git plugin
> [JENKINS-73471] Git scm.userRemoteConfigs.credentialsId configured by Bitbucket is null

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceContext.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketBuildStatus.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTrait/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTrait/help-disableNotificationForNotBuildJobs.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTrait/help-sendStoppedNotificationForAbortBuild.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTrait/help-sendSuccessNotificationForUnstableBuild.html
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications2Test.java
Adds an option to the Status Notification Trait to guide what notification to send to Bitbucket when the Jenkins build result is ABORTED.
This PR restores the default behavior for the NOT_BUILT notification from SUCCESS to FAILED (configurable to STOPPED) for Bitbucket Cloud; the SUCCESS state was incorrectly introduced in 2022 as the default instead of STOPPED when the disableNotificationForNotBuildJob configuration option was added (the name can be misinterpreted).
Adds missing guidance description for each configurable option in the Build Status Notification Trait.
Status Notification Summary
| Jenkins | Bitbucket Cloud | Bitbucket Data Center and Server |
| --- | --- | --- |
| [SUCCESS](https://javadoc.jenkins.io/hudson/model/Result.html#SUCCESS) | SUCCESSFUL | SUCCESSFUL |
| …
> Use CANCELLED build state in Bitbucket Data Center and Server 8.0 (#606)

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
This fix the issue reported in comment https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/898#issuecomment-2474278089 that prevent to update bitbucket plugin version in BOM and cause regression in Blue Ocean unit test.
To test again using this incremential build in blue ocean plugin on `io.jenkins.blueocean.blueocean_bitbucket_pipeline.cloud.BbCloudPipelineCreateRequestTest`
> Fix missing primary clone links in BitbucketSCMSource when retrieve branches and pull requests using REST APIs

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
Add an alias to fix XStream serialisation
Need to add unit test with an old config.xml with
`<com.cloudbees.jenkins.plugins.bitbucket.MergeWithGitSCMExtension plugin="cloudbees-bitbucket-branch-source@886.v44cf5e4ecec5">`
> [JENKINS-74848] Issue in config.xml CannotResolveClassException: com.cloudbees.jenkins.plugins.bitbucket.MergeWithGitSCMExtension

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketOAuthAuthenticator.java
Change the configured http client provider in scribejava from Apache HTTP Client to JDK HTTP Client, as in the previous implementation with the scribe library. There is no gain in using a client with a pooled connection manager that is destroyed every time a new token is requested.
This commit fix the ClassNotFoundException issue of org.apache.logging.log4j.spi.LoggerAdapter (commons-logging is marked as a scope dependency in the pom-plugin) when scm is used in a scripted pipeline.
> Fix leaking of Apache HTTP client I/O Dispatcher threads

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMRevision.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceTest.java
Revert to the behavior before the clone link feature from version 866. The remote URL must not contain the user or it may not work when using username/password authentication. This is because the username belonging to the credential provided to perform the git operation may not be the same as the URL. The clone URL comes from the links that bitbucket sends with the repository information. The link sent contains the user associated with the credentials used to call the REST APIs.
> [JENKINS-73250] The GIT_URL environmente variable contains user name after update

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/SSHCheckoutTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/ClosingConnectionInputStream.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/internal/api/AbstractBitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClientTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketIntegrationClientFactory.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClientTest.java
Improve error logging from the bitbucket client. This helps to understand what is going wrong (e.g. HTTP 403).
Reduce duplicate code by sharing Apache HTTP client management between bitbucket server and cloud clients
> CQI Improve error logging from the bitbucket client

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketUsernamePasswordAuthenticator.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceTest.java
Fix null credentialsId passed to GitSCM when authentication is username/password or the StandardUsernameCredential provided by the BitbucketAuthenticator is null.
> Fix HTTP token authentication for bitbucket server

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketOAuthAuthenticator.java
This issue is caused by removing user from clone link. Using "x-token-auth" as user tells bitbucket that the specified password is an OAuth2 credential token.
> Fix git clone of repository using OAuth2 authenticator.

- .gitignore
- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketBuildStatus.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/internal/api/AbstractBitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClientTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketIntegrationClientFactory.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClientTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/payload/2.0-repositories-amuniz-test-repos-commit-046d9a3c1532acf4cf08fe93235c00e4d673c1d3-statuses-build.json
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/build-status-1.0-commits-046d9a3c1532acf4cf08fe93235c00e4d673c1d3.json
For bitbucket Server and Cloud:
* name must be less than 255 characters;
* URL must be less than 450 characters, in this case we can not trim otherwise the URL is invalid.
> Fix the API build notification state when the sent payload contains a longer than allowed attribute value.

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketOAuthCredentialMatcher.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketUsernamePasswordCredentialMatcher.java
Remove the CredentialsMatcher.CQL implementations that generated invalid Credentials Query Language (CQL) expressions.
CQL is a feature originally added in [JENKINS-35306](https://issues.jenkins.io/browse/JENKINS-35306) that lets a credential provider convert a CredentialMatcher to an expression tree and then check whether this expression matches a credential, without even loading the credential to the JVM.  For example, a credential provider that stores credentials in an SQL database could convert CQL to SQL and load only matching credentials from the database.  However, CQL does not support all the checks that BitbucketOAuthCredentialMatcher and BitbucketUsernamePasswordCredentialMatcher do.  Those classes generated invalid CQL that could not be parsed.  Although it might be possible to …
> Remove CredentialsMatcher.CQL implementations

- pom.xml
The [933.0.1 pom file](https://repo.jenkins-ci.org/artifactory/releases/org/jenkins-ci/plugins/cloudbees-bitbucket-branch-source/933.0.1/cloudbees-bitbucket-branch-source-933.0.1.pom) stored in the Jenkins artifact repository includes an invalid scm.tag value because the tagNameFormat property was removed on the 933.x branch.
[Apache Maven release plugin documentation](https://maven.apache.org/maven-release/maven-release-plugin/prepare-mojo.html#tagNameFormat) says the default tagNameFormat is '@{project.artifactId}-@{project.version}'.  That matches with the value that is in the pom file, 'cloudbees-bitbucket-branch-source-933.0.1'.  It does not match the value written to the git repository.
The 933.0.1 release cannot be included in the Jenkins plugin BOM because of that invalid scm.tag. …
> Use tagNameFormat to include correct tag in released pom file

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketApiUtils.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
Adapt the refname format in the build status to follow that explained in https://issues.jenkins.io/browse/JENKINS-75015 as undocumented feature.
> [JENKINS-75015] Update the build status refname format used for Bitbucket Cloud

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/extension/BitbucketEnvVarExtension.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/payload/2.0-repositories-amuniz-test-repos.json
Fix BitbucketEnvVarExtension to be compatible with @DataBoundConstructor annotation. Add getter methods, hashCode and equals method and a own GitSCMExtensionDescriptor.
Add test cases
> [JENKINS-53535] Make Bitbucket Server, Owner and repository environment variables for Bitbucket Team/Project based jobs

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketDefaultBranch.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketProject.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/AbstractBitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/ExponentialBackOffServiceUnavailableRetryStrategy.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketIntegrationClientFactory.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfigurationTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/ExponentialBackOffServiceUnavailableRetryStrategyTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClientTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-browse-Jenkinsfile_at_feature_2Fpipeline.json
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz-repos-test-repos-browse-folder-Jenkinsfile_at_feature_2Fpipeline.json
Refactory both server/cloud client to share the client management.
Use apache http client configuration to retry on HTTP 429 (too many connection) response.
> [JENKINS-64418] Add exponential backoff to BitBucket rate limit retry loop

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/notifier/BitbucketBuildStatusNotifications.java
When posting a build status from a pull-request job to Bitbucket Server or Data Center, set the "ref" property to match the source branch, e.g. "refs/heads/myfeature".  This fixes the problem that Bitbucket Server stopped showing build statuses in the list of pull requests when the plugin started using the newer build-status API in <https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/930>.
This PR does not change how the plugin posts a build status to Bitbucket Cloud.  That case will have `"ref": null` for pull-request jobs, like before.
Fix [JENKINS-75083](https://issues.jenkins.io/browse/JENKINS-75083).
Manually tested with Bitbucket Server; see <https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/954#issuecomment-2571190504>.
> [JENKINS-75083] Build statuses do not appear in list of pull requests in Bitbucket Server

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/AbstractBitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketIntegrationClientFactory.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClientTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/mirroring-latest-upstreamServers-1-repos-1_jwt_TOKEN.json
Fix the method to retrieve the list of mirror URLs without using authentication. A JWT token is already provided in the request URL as documented at https://developer.atlassian.com/server/bitbucket/rest/v803/api-group-mirroring/#api-mirroring-latest-repos-repoid-mirrors-get
> [JENKINS-75089] Getting clone URL using mirror returns HTTP 401

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
Commit e4d32d549b3bf29a896ae0ec31f2d88cbcb32377 (<https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/927> for [JENKINS-64418](https://issues.jenkins.io/browse/JENKINS-64418)) introduced a bug that duplicates the base URL in some HTTP requests to Bitbucket Server, causing an error like this:
```
java.io.FileNotFoundException: URL: https://bitbucket.examplehttps://bitbucket.example/rest/api/1.0/projects/DEMO/repos/demo/branches?filterText=master&start=0&limit=200
at com.cloudbees.jenkins.plugins.bitbucket.impl.client.AbstractBitbucketApi.doRequest
java.io.IOException: Communication error for url: GET https://bitbucket.examplehttps://bitbucket.example/rest/api/1.0/projects/DEMOrepos/demo/branches?filterText=master&start=0&limit=200 HTTP/1.1
at …
```
> [JENKINS-64418] Fix duplicate base URL in request to Bitbucket Server

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiFactory.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/AbstractBitbucketEndpoint.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfiguration.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookAutoRegisterListener.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/util/BitbucketApiUtils.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/util/BitbucketCredentials.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClientTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java
If the number of server instances is only one, when a new Jenkins project is created the server list combobox is not available. This causes, in the UI component that loads credentials, to pass the stapler parameter serverUrl as an empty string.
In this scenario, serverUrl must be taken from the first of configured endpoints so that it can properly filter the list of credentials.
Test why and the use case to normalizeServerUrl must be bitbucket cloud if server url is null
> [JENKINS-75073] Missing serverUrl in fillCredentialsIdItems cause some credentials missing in the initial configuration

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/AbstractNativeServerSCMHeadEvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/AbstractSCMHeadEvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/BitbucketSCMSourcePushHookReceiver.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookEventType.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPingHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPullRequestHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPushHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PREvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PushEvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PushHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/ServerHeadEvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/ServerPushEvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/util/URLUtils.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/BitbucketSCMSourcePushHookReceiverTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessorTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfigurationTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/util/URLUtilsTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/hooks/cloud/pullrequest_created.json
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/hooks/cloud/pullrequest_rejected.json
Move test to JUnit5 and add processor unit test
Add unit test for hook processor when process pull request.
Consider to add other events for tag, new commit and so on
> Extract event anonymous inner classes from webhook processor.

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClientTest.java
Fix issue in the bitbucket server client when is built the Apache HttpHost from the serverURL. If the Bitbucket Server is installed under a context root different than root ("/"), than the HttpHost built parsing the entire given serverURL throw an UnknownHostException failure in the client. The fix removes the file part of the serverURL
> [JENKINS-75119] Build report UnknownHostException in console log for Bitbucket Server when the server instance is under a context root

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFile.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/AbstractBitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketIntegrationClientFactory.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileTest.java
Remove the HttpHost parameter when calling in Apache client as it seems to cause a 404 error in the response while in previous version the call worked.
> [JENKINS-75157] Bitbucket client fail to retrieve resource with HTTP 404 for bitbucket server

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/AbstractBitbucketApi.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClientTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClientTest.java
Fix proxy configuration to be used in the Apache client created from the ProxyConfiguration class using only the hostname instead passing the configured serverURL. The NO_PROXY configuration matches only hostname, that means if the given hostname contains also scheme or port match fails.
> [JENKINS-75160] NO_PROXY configuration seems to be ignored

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketOAuthCredentialMatcher.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketUsernamePasswordCredentialMatcher.java
Add a try catch block in CredentialsMatcher implementation when invoke UsernamePasswordCredentials#getPassword method to handle those implementations that perform some operations, like an HTTP call, for which throw an exception.
> [JENKINS-75184] CredentialsMatcher fail with ECR Security Token

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketAccessTokenAuthenticatorSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketAuthenticatorUtils.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketOAuthCredentialMatcher.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketUsernamePasswordCredentialMatcher.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketOAuthCredentialMatcherTest.java
Limit the amount of time required to decryipt a password in case of com.cloudbees.jenkins.plugins.amazonecr.AmazonECSRegistryCredential credentials that takes long because perform rest operation to return password from the amazon vault.
> [JENKINS-75225] When configure job the list of credentials returns HTTP 504

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/repository/BitbucketRepositorySource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFile.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/payload/2.0-repositories-amuniz-test-repos-src-folder_2Ffile.properties_at_master.json
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/payload/2.0-repositories-amuniz-test-repos-src-master-folder_2Ffile.properties_format_meta.json
Fix cloud client when file metadata return a path attribute that contains '/', for example 'scripts/Jenkinsfile'
> [JENKINS-75208] Checkout on bitbucket server fail with IllegalArgumentException "Name cannot contain '/'"

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketTagSCMHead.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/ServerPushEvent.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketIntegrationClientFactory.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPushHookProcessorTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/hooks/native/tagPayload.json
Fix the timestamp in BitbucketTagSCMHead valued with 0 in NativeServer webhook processor instead of the annotated tag timestamp or using the referred commit timestamp.
This is archived perforing a remote call to get missing details in the event payload, unfortunately there are no real example to implement a different strategy.
Fix #642
> BitbucketTagSCMHead does not receive an annotated tag date

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceContext.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketBuildStatus.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/AbstractBitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/notifier/BitbucketBuildStatusNotifications.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTrait/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTrait/help-useReadableNotificationIds.html
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClientTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/notifier/BitbucketBuildStatusNotificationsJUnit5Test.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClientTest.java
Add an option in the build status notifications trait to use as id of the notification an human readable format so it is possible configure a filter in the Bitbucket server as described in https://confluence.atlassian.com/bitbucketserver/checks-for-merging-pull-requests-776640039.html
[X] rename hashNotificationIds to useReadableIds
[X] add documentation in the help file (add a note when you change current setting that current notifications will be doubled)
[X] add test cases
[X] force notification id to be upper or lowercase so it not subject to the owner name cases
[X] verify the max key length and strategy to reduce it
> [JENKINS-72780] The key value for the build notification is an UUID which couldn't be filter in required build feature of Bitbucket

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketOAuthAuthenticator.java
Cache is set to expire after 5 minutes.
> Add cache for OAuth2 token to reduce the number of requests.

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/notifier/BitbucketBuildStatusNotifications.java
Set the "refname" attribute of the build status notification so that Bitbucket Cloud can display only the correct status when a commit is the subject to multiple PRs
> Set the "refname" attribute of the build status notification

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketBuildStatus.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/notifier/BitbucketBuildStatusNotifications.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/notifier/BitbucketBuildStatusNotificationsJUnit5Test.java
Include parent key into build status notification to be abler to use the required build feature in bitbucket
The parent key is calculated from the parent of the build.
https://issues.jenkins.io/browse/JENKINS-75203
> [JENKINS-75203] Include parent in build status notification

- README.md
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/repository/BitbucketServerProject.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClientTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/server/payload/1.0-projects-amuniz.json
Fix wrong avatar URL in BitbucketServerProject
> [JENKINS-75440] OrganizationFolder does not show Bitbucket DC project avatar

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/ClosingConnectionInputStream.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/AbstractBitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketUsernamePasswordAuthenticator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/ExponentialBackOffRetryStrategyTest.java
Using a basic credentials provider with preemptive authentication does not work as expected.
Remove socket timeout configuration because it impact any socket connection not only the current request.
> Fix basic authentication for BitbucketUsernamePasswordAuthenticator

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/trait/DiscardOldTagTrait.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/Messages.properties
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/trait/DiscardOldTagTrait/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/trait/DiscardOldTagTrait/help-keepForDays.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/trait/DiscardOldTagTrait/help.html
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/trait/DiscardOldTagTraitTest.java
> Add a new trait to discard all tags with creation date older than the configured days

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/branch/BitbucketServerCommit.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/trait/DiscardOldBranchTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/trait/DiscardOldTagTrait.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/trait/DiscardOldTagTrait/help-keepForDays.html
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMRevisionTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/trait/DiscardOldTagTraitTest.java
Change authorTimestamp to committerTimestamp for Bitbucket DataCenter commit details to reflect the same date that Bitbucket Cloud send in the commit details. Improve help of DiscardOldTagTrait
> [JENKINS-75534] DiscardOldBranch trait uses AuthorDate of HEAD commit to determine branch age rather than CommitDate

- README.md
- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/PullRequestSCMHead.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/PullRequestBranchType.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/pullrequest/BitbucketPullRequestValueRepository.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/AbstractBitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/branch/BitbucketServerBranch.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/pullrequest/BitbucketServerPullRequestSource.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilderTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPullRequestHookProcessorTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/notifier/BitbucketBuildStatusNotificationsJUnit5Test.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/hooks/native/prOpenFromTagPayload.json
Add a new branchType field in the pull request bean that is used to identify in case of pull requests for which the source HEAD is a tag instead of branch. This kind of pull request are available only in Bitbucket DataCenter. Failure during checkout of PR jobs from HEAD tag has been resolved using as source reference "+refs/tags/<tag_name>:..." instead of "+refs/heads/<tag_name>:...".
> [JENKINS-75523] PRs created from tags cannot be checked out

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/extension/GitClientAuthenticatorExtension.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/util/BitbucketCredentials.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceTest.java
The git extension is used to pass inject credentials into the git client before checkout, these changes remove credentials implementation stored in config.xml that potentially could not be updated and cause an authentication failure hidden behind other IOException.
> Rework the GitClientAuthenticatorExtension

- checkstyle.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/PullRequestSCMRevision.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/branch/BitbucketCloudAuthor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/pullrequest/BitbucketCloudPullRequestCommit.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPushHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/util/BitbucketApiUtils.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/util/SCMUtils.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketClientMockUtils.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilderTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/client/payload/2.0-repositories-amuniz-test-repos-pullrequests-1.json
Fix building of a GitSCM by BitbucketGitSCM in case of revision from a Pull Request web hook event that contains an abbreviate 7 chars of a SHA1 commit hash.
> [JENKINS-75555] InvalidObjectIdException when "Scan Project Now" and multibranch-build-strategy plugin is installed

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMRevision.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketAuthenticator.java
Fix the credentialsId passed to the SCMBuilder from the SCMSorce using the credentials that be used to checkout from the remote.
> [JENKINS-75611] Disabling HTTPS cloning protocol on Data Center causes builds to fail even if SSH checkout feature is configured

- docs/USER_GUIDE.adoc
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketAuthenticatorUtils.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketOAuthAuthenticator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/util/BitbucketApiUtils.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketAuthenticatorUtilsTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/util/BitbucketApiUtilsTest.java
Add token cache lease time configurable by bitbucket.oauth2.cache.timeout system property.
Fix unwrapping exception utility method.
> [JENKINS-75466] Notifying commit build result sometimes returns HTTP 404

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfiguration.java
Blue Ocean Bitbucket plugin depends on this plugin and uses the BitbucketEndpointConfiguration.normalizeServerUrl method.  Rather than require a new release of Blue Ocean, let's retain compatibility by restoring that method and marking it as deprecated.
Detected in:
* https://github.com/jenkinsci/bom/issues/5076
* https://github.com/jenkinsci/bom/pull/5088
```
mvn -Dtest=BitbucketSCMNavigatorTest,BitbucketEndpointConfigurationTest,BitbucketServerEndpointTest,BitbucketSCMNavigatorTest clean verify
```
Will use the incremental build of this pull request in:
* https://github.com/jenkinsci/bom/pull/5088
> Restore BitbucketEndpointConfiguration.normalizeServerUrl() for compatibility

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java
Remove hook secret when register webhook for PLUGIN implementation.
> [JENKINS-75804] Webhook auto registration fail with PLUGIN implementation

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/BitbucketTlsSocketStrategy.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/credentials/BitbucketClientCertificateAuthenticator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
Fix using a library that allow to hotswap client certificates for an existing SSLContext.
Implementation based on this documentation:
https://github.com/Hakky54/sslcontext-kickstart?tab=readme-ov-file#support-for-swapping-keymanager-and-trustmanager-at-runtime
> [JENKINS-75676] Client certificate credentials not handled properly

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/endpoint/BitbucketEndpointProvider.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/webhook/BitbucketWebhookConfigurationBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/webhook/BitbucketWebhookConfigurationsBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/webhook/NativeBitbucketWebhookConfigurationBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/endpoint/BitbucketCloudEndpoint.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/webhook/AbstractBitbucketWebhookConfigurationBuilderImpl.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/webhook/cloud/CloudWebhookConfigurationBuilderImpl.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/webhook/plugin/PluginWebhookConfiguration.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/webhook/plugin/PluginWebhookConfigurationBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/webhook/server/ServerWebhookConfiguration.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/webhook/server/ServerWebhookConfigurationBuilderImpl.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/api/webhook/BitbucketWebhookConfigurationsBuilderTest.java
Add new API interfaces to lookup builder used to instantiate a BitbucketWebhookConfiguration.
Example of usage:
```
NativeBitbucketWebhookConfigurationBuilder builder = BitbucketWebhookConfigurationsBuilder.lookup("CLOUD_NATIVE", NativeBitbucketWebhookConfigurationBuilder.class);
builder.autoManaged("adminCredentialsId");
builder.callbackRootURL("https://jenkins.acme.com/jenkins");
builder.signature("signatureCredentialsId");
BitbucketWebhookConfiguration webhook = builder.build();
```
See test case in the PR for other examples
> [JENKINS-76108] Alternative for setManageHooks
