- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/BitbucketSCMSourcePushHookReceiver.java
[JENKINS-36399](https://issues.jenkins-ci.org/browse/JENKINS-36399)
Fix Problem with CSRF Protection by porting the patch from the bitbucket-plugin
see: https://github.com/jenkinsci/bitbucket-plugin/commit/9ace547bbc36c44e8407541ce8be405ccc82d9bc
> [JENKINS-36399] Add/port CrumbExclusion

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEvent.java
> Fix JENKINS-36400

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
First let me say that this is my first PR using java. 
I've forked @kmadel work and implemented "In Progress" status using the checkout listener (I'm trying to copy somehow what Github is doing).
Hope you can help me to improve any missing stuff. I really need this functionality (and others to come).
> Trying to implement Commit status with "In progress"

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
[JENKINS-39267](https://issues.jenkins-ci.org/browse/JENKINS-39267)
> [JENKINS-39267] Honour the no_proxy setting when connecting to BitBucket

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketDefaultBranch.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketRepoMetadataAction.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
See [JENKINS-40835](https://issues.jenkins-ci.org/browse/JENKINS-40835)
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/20
@reviewbybees
> [FIXED JENKINS-40835] Report primary branch

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/PullRequestSCMHead.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/SCMHeadWithOwnerAndRepo.java
See [JENKINS-41313](https://issues.jenkins-ci.org/browse/JENKINS-41313)
@reviewbybees
> [JENKINS-41313] Fix-up Pull Request heads after upgrade

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
See [JENKINS-41464](https://issues.jenkins-ci.org/browse/JENKINS-41464)
@reviewbybees esp @vivek
> [JENKINS-41464] Attach ContributorMetadataAction to PRs

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator/config.jelly
See [JENKINS-39898](https://issues.jenkins-ci.org/browse/JENKINS-39898)
@reviewbybees
> [FIXED JENKINS-39898] Expose the includes/excludes branches in BitbucketSCMNavigator

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketTeam.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/package-info.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/repository/BitbucketCloudTeam.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/repository/BitbucketServerProject.java
See [JENKINS-42795](https://issues.jenkins-ci.org/browse/JENKINS-42795)
@reviewbybees
> [FIXED JENKINS-42795] Incorrect type mapping of href deserialization in team objects

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
Used for various diagnostic purposes and may be used by https://github.com/jenkinsci/blueocean-plugin/pull/1010.
@reviewbybees esp. @vivek
> MercurialRevision should implement toString to return the hash

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketHref.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketRepository.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/repository/BitbucketCloudRepository.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PushHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/repository/BitbucketServerRepository.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator/help-sshPort.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource/config-detail.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource/help-sshPort.html
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketClientMockUtils.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEventTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPushEventTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/events/BitbucketServerPullRequestEventTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/events/BitbucketServerPushEventTest.java
See [JENKINS-44413](https://issues.jenkins-ci.org/browse/JENKINS-44413)
@reviewbybees
> [FIXED JENKINS-44413] Replaced configuration of SSH port with retrieval from the API

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketTeamMetadataAction.java
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/44
@reviewbybees
> [JENKINS-45434] Serve avatars now that we have an image resizing servie

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/45
> [JENKINS-45436] Pick up SCMName API

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PushHookProcessor.java
See [JENKINS-45533](https://issues.jenkins-ci.org/browse/JENKINS-45533)
@reviewbybees
> [FIXED JENKINS-45533] Correctly check for Bitbucket Cloud server url

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/MergeWithGitSCMExtension.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilderTest.java
See [JENKINS-45771](https://issues.jenkins-ci.org/browse/JENKINS-45771)
Downstream of https://github.com/jenkinsci/git-plugin/pull/516 and https://github.com/jenkinsci/git-client-plugin/pull/255
@reviewbybees
> [JENKINS-45771] Pick up consolidated MergeWithGitSCMExtension from git plugin

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketBranch.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/branch/BitbucketCloudBranch.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/events/BitbucketCloudPullRequestEvent.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/branch/BitbucketServerBranch.java
Timestamp extraction tested with [atlassian/bitbucket-server:4.3](https://hub.docker.com/r/atlassian/bitbucket-server/) and Bitbucket Cloud
> [JENKINS-46589] include branch tip modification timestamps

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
[JENKINS-45775](https://issues.jenkins-ci.org/browse/JENKINS-45775)
For Bitbucket Server, use destination repository.
Find source commit hash by searching in PRs
> Fix JENKINS-45775

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BranchSCMHead.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/PullRequestSCMHead.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/Messages.properties
Working on Office 365 Connector plugin I was dishearten by the lack of pronouns 😞 
Let's fix it 🍰 🚀
> Pronouns, pretty please

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessor.java
See [JENKINS-47675](https://issues.jenkins-ci.org/browse/JENKINS-47675)
> [FIXED JENKINS-47675] mirror changes from 45775 in event code

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/Utils.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/repository/BitbucketRepositorySource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFile.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerApiFactory.java
Replaces https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/75.
> [FIXED JENKINS-42518] Add support for lightweight checkout

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookAutoRegisterListener.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/WebhooksAutoregisterTest.java
See https://javaadventure.blogspot.ie/2016/12/the-costs-of-java-utils-logging.html for a benchmark that confirms the cost
@i386 @batmat
> Friends don't let firends use String.format in logging statements

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
Reported on https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/78#issuecomment-343090109
> Avoid double String.format()

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
Hello guys!
This is a fix for https://issues.jenkins-ci.org/browse/JENKINS-45891
I have implemented the fix suggested by [Sven here](https://issues.jenkins-ci.org/browse/JENKINS-45891?focusedCommentId=313514&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-313514) and it seems it work.
Thx
> JENKINS-45891 - fix 'cannot resolve upstream (mixed local/remote)'

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/branch/BitbucketServerBranch.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/branch/BitbucketServerBranches.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/pullrequest/BitbucketServerPullRequests.java
See [JENKINS-47653](https://issues.jenkins-ci.org/browse/JENKINS-47653)
> [FIXED JENKINS-47653] Lazy evaluation of branch last modified timestamp for Bitbucket Server

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/Utils.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
See [JENKINS-47978](https://issues.jenkins-ci.org/browse/JENKINS-47978)
Closes #84
> [FIXED JENKINS-47978] Fix all the encoding mess that breaks lightweight checkout

- pom.xml
Should help things show up on wiki/plugin side
cc @amuniz sorry I didn't realise this was you!
> add developer section to clarify contributors

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
Not to escape path separator.
BitbucketServerAPIClient uses internaly HttpClientBuilder.create() so I can't create unit tests for this change.
> JENKINS-49671 Check if file exists - available for file in subdirectory

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
Fixes https://issues.jenkins-ci.org/browse/JENKINS-49709
> JENKINS-49709 Fix Proxy Initialization

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceRequest.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketTagSCMHead.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/TagDiscoveryTrait.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/Messages.properties
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/TagDiscoveryTrait/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/TagDiscoveryTrait/help.html
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigatorTest.java
> JENKINS-47254 : support bitbucket tags

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiFactory.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/Cache.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketCloudEndpoint.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketCloudEndpoint/config-detail.jelly
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/UriResolverTest.java
in servers global configuration
> JENKINS-50314 : Using or not caches should be configurable

- .mvn/extensions.xml
- .mvn/maven.config
- pom.xml
Support for incremental would be nice for this repo, to speed up the deployment of PRs for extension plugins! Please consider merging 👍 
See [JEP-305 for context](https://github.com/jenkinsci/jep/blob/master/jep/305/README.adoc)
> Incrementals

- pom.xml
fix indent for developers
@amuniz 🙌 Please consider approving https://github.com/jenkins-infra/repository-permissions-updater/pull/835
> add casz as developer

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
This reverts commit 359a60f9ffb066925f4ad95c5d2fe6db6ab47b7c.
> Revert "Merge pull request #147 from Nuglif/fix_notification"

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
Otherwise throw an IOException, fixes #JENKINS-55068
> [JENKINS-55068] Only consider 404 as path does not exist

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMRevision.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
As requested by @nfalco79 (see [this comment](https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/156#discussion_r242885607)), this fixes an issue introduced in commit e676433e67942e997a50d6fb7f580416c2557e58.
> Fix equals & hashcode

- src/main/resources/index.jelly
> index.jelly : update description to reflect support for Bitbucket Server

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketHgSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/SSHCheckoutTrait.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilderTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketHgSCMBuilderTest.java
> [JENKINS-46094] Fix SSH Clone trait using agent credentials

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketCloudEndpoint.java
Current rendering is like this:
With some changes I'm working on, it might look like this:
The floating is part of the way this thing is designed, if my screen were really wide, the "done" would be very divorced from the button in the current system as well. Done is not a helpful message.
> Improve output

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClientTest.java
Addressing regression introduced by https://github.com/brainbeanapps/bitbucket-branch-source-plugin/commit/868676d61ce3847547b6860b928d07c1679c144f in version 2.4.3 (https://issues.jenkins-ci.org/browse/JENKINS-56926)
> [JENKINS-56926] Restore support of Jenkinsfile located in subdirectory

- checkstyle.xml
Fixes `NewlineAtEndOfFile: File does not end with a newline.` on Windows
> fix checkstyle line separator to lf

- .github/pull_request_template.md
- .github/release-drafter.yml
Simplified pull request template.
Also switched to extending jenkinsci/.github release drafter
> Simplified pull request template

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketAuthenticator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPullRequestHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMRevisionTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigatorTest.java
> Fix codacy issues

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketTeamMetadataAction.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/AbstractBitbucketTeam.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketTeam.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/avatars/AvatarCache.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/avatars/AvatarCacheSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/avatars/UrlAvatarCacheSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/repository/BitbucketCloudTeam.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/repository/BitbucketServerProject.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketIntegrationClientFactory.java
As per #183 
* Added a copy of AvatarCache from https://github.com/jenkinsci/scm-api-plugin, altered to allow provision of custom AvatarCacheSource source for Images (in future to be added back to scm-api-plugin)
* Implement Bitbucket specific AvatarCacheSource
* Add `getTeamAvatar()` to BitbucketAPI and its implementations
Still work in progress as it needs to be tested
> Add support for Avatars for authenticated teams/projects

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/PullRequestSCMHead.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/SCMHeadWithOwnerAndRepo.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilderTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketHgSCMBuilderTest.java
The title of a merge request is important information. I'd prefer to add this into its super interface. Also, the jenkinsci/scm-api-plugin#77 is on its way.
> Add PR's title into PullRequestSCMHead

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/branch/BitbucketServerBranch.java
When you have multiple jobs on the same branch, you can get into concurrency issues and null pointer exceptions.
> Fix NullPointerException and Concurrency Issues

- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BranchDiscoveryTrait/help-strategyId.html
This PR updates the copy for the "Only branches that are also filed as PRs" branch discovery mode to list use cases.
> Update copy on branch discovery to not imply deprecation.

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookEventType.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPullRequestHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java
Added a couple of events to the list of events that get processed.
https://issues.jenkins-ci.org/browse/JENKINS-60751
- [x ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x ] Ensure that the pull request title represents the desired changelog entry
- [x ] Please describe what you did
- [x ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
> [JENKINS-60751] - Add listener to new bitbucket events

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/BitbucketServerVersion.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/BitbucketServerWebhookImplementation.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint/config-detail.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint/help-serverVersion.html
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest/configuration-as-code.yml
This works around incompatibilities between older versions of bitbucket and bitbucket v7.x.
Added an option to let users specify their version.
Fixes #326
> Add Bitbucket Server Version option

- .mvn/extensions.xml
- pom.xml
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java
For PCT compat w/ https://github.com/jenkinsci/jenkins/pull/4848.
> Let BitbucketEndpointConfigurationTest tolerate Spring Security version of AccessDeniedException

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
[JENKINS-48828](https://issues.jenkins-ci.org/browse/JENKINS-48828)
There was an error being throw when viewing the multibranch pipeline children of a Bitbucket Team job.  
The error was being thrown from `doFillRepositoryItems`:
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/24d9487c9dcdc6e5f00f9c891b162da3bba3cb3c/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java#L1191-L1212
The equivalent method in `github-branch-source` is quite a bit different:
https://github.com/jenkinsci/github-branch-source-plugin/blob/490693b59b83a4a82b0b94dd1ba2c7b5870be005/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java#L2161-L2180
This change makes the method here look like the method in `github-branch-source`.
Tested manually with and …
> [JENKINS-48828] Fix mistaken doFillRepositoryItems AccessDenied

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource/config-detail.jelly
https://issues.jenkins-ci.org/plugins/servlet/mobile#issue/JENKINS-64125
Select inside invisibleEntry is not being populated by the backend since 2.244
- [x ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x ] Ensure that the pull request title represents the desired changelog entry
- [x ] Please describe what you did
- [ x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org/plugins/servlet/mobile#issue/JENKINS-64125)
> JENKINS-64125 removing hidden fields

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
> no break a search when 401 is returned

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
> [JENKINS-65718] in case of merged PR bitbucket server can return status 409 so in this case we must mark pull request as not mergeable

- pom.xml
> Update bom and minimum Jenkins version 2.222.x

- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator/help-repoOwner.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator/help-serverUrl.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource/help-repoOwner.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource/help-serverUrl.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/ForkPullRequestDiscoveryTrait/help-strategyId.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/OriginPullRequestDiscoveryTrait/help-strategyId.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/SSHCheckoutTrait/help-credentialsId.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint/help-serverUrl.html
The pattern is to have a main help line followed by more details.
No `<p>` is used after the `<div>` as it would add non desired padding.
> Improve layout of help texts

- .github/workflows/cd.yml
Completely forgot about this :)
> add cd workflow

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotificationsTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketClientMockUtils.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchScanningIntegrationTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BranchScanningTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/SCMNavigatorIntegrationTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/SCMNavigatorTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/UriResolverTest.java
- src/test/java/integration/ScanningFailuresTest.java
Hello everybody,
this PR reduce usage of BitbucketRepositoryType. May be it's of interest. It's a first pull-request of
multiple i'll raise. The first attempt to remove BitbucketRepositoryType completely, was not a good idea :-)
Greetings,
Alexander
> Reduce usage of deprecated BitbucketRepositoryType.

- pom.xml
- src/test/java/integration/ScanningFailuresTest.java
> bump jenkins-bom 2.289.x

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudPage.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint.java
- src/test/java/integration/ScanningFailuresTest.java
Next PR from my side. This time using check annotation consistently.
Greeting,
Alexander
> Use annotations consistently.

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPullRequestHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPushHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PushHookProcessor.java
Basically just copy paste from the GitHub plugin. Fixes issue with rebases and incorrect revision being detected #527 (tested on local jenkins)
Possible would be helpful for #469
> Add event delay to BitbucketSCMSource (Default: 5s)

- pom.xml
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfigurationTest.java
https://github.com/jenkinsci/jenkins/pull/6025#discussion_r766968432
> Adapting to https://github.com/jenkinsci/jenkins/pull/6025

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceBuilder.java
Problem was introduced in #796.
Was mentioned in comment https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/796#discussion_r1487720255
> Fix compatibility with Blue Ocean plugin

- pom.xml
@rsandell did not respond to https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/817#discussion_r1506768675.
> Slim down JPI

- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator/help-serverUrl.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource/help-serverUrl.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/WebhookRegistrationTrait/help-mode.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/WebhookRegistrationTrait/help.html
> Update 'Configure Jenkins' to 'System'

- .github/workflows/codeql.yml
- pom.xml
Bump org.jenkins-ci.plugins:plugin from 4.88 to 5.3
Bump io.jenkins.tools.bom:bom-2.462.x from 3654.v237e4a_f2d8da_ to 3696.vb_b_4e2d1a_0542
> Bump org.jenkins-ci.plugins:plugin from 4.88 to 5.3

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMRevision.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilderTest.java
> Use BitbucketServer repository browser for Data Center or Server

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/trait/DiscardOldBranchTrait.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/trait/DiscardOldBranchTraitTest.java
Fix the expiry date to consider the keepForDays value
> [JENKINS-75340] DiscardOldBranchTrait doesn't respect keepForDays

- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint/help-callCanMerge.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint/help-callChanges.html
- src/main/resources/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint/help-webhookImplementation.html
Minor typo and abbreviation fixes.
- [ x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [ x] Please describe what you did
> Improve help texts

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/impl/client/AbstractBitbucketApi.java
Improve message when bitbucket client returns HTTP 404
> [JENKINS-75466] Notifying commit build result sometimes returns HTTP 404

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMNavigator.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceRequest.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketApi.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketRepository.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/BitbucketSCMSourcePushHookReceiver.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookProcessor.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/ServerPushEvent.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSourceBuildTest.java
Remove declaration of InterruptedException that is never thrown by the client.
Fix log message in the wrong format
Remove compile warning about useless suppress annotations
> Cleanup code

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java
Remove hook secret when register webhook for PLUGIN implementation.
> [JENKINS-75804] Webhook auto registration fail with PLUGIN implementation

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/AbstractBitbucketEndpoint.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketCloudEndpoint.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketEndpointConfiguration.java
- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/endpoints/BitbucketServerEndpoint.java
Backport the fix from commit 24931a44e106ab1c28dc37b22f5a29d5e4643c5c for the Describable of BitbucketEndpoint configuration
> [JENKINS-75762] The Bitbucket global configuration page does not list any available endpoints type

- src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/BitbucketSCMSourcePushHookReceiver.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/BitbucketSCMSourcePushHookReceiverTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookAutoRegisterListenerTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/webhook/cloud/CloudPullRequestWebhookProcessorTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/webhook/cloud/CloudPushWebhookProcessorTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/webhook/plugin/PluginPullRequestWebhookProcessorTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/webhook/plugin/PluginPushWebhookProcessorTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/impl/webhook/server/ServerPushWebhookProcessorTest.java
- src/test/java/com/cloudbees/jenkins/plugins/bitbucket/test/util/HookProcessorTestUtil.java
Make the copy of headers case insensitive.
> [JENKINS-76086] Fails to process Bitbucket webhook events with "No processor found"
